apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zsuuz7w72-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zsuuz7w72-go 
  name: zsuuz7w72-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zsuuz7w72-go 
