apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: zsuuz7w72-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:42caa07cd90a935c8b12e7937f1d680ac5cdd6a9@sha256:2ed89752f08f3e79553c02c3300f36e497c66c4f764a2ffe5186e552f699c7ce
          name: container-image
